from pathlib import Path

import numpy as np

from persistence import Database
from persistence.project_repository import ProjectRepository
from services.AudioService import AudioService
from services.FileService import FileService
from services.ProjectService import ProjectService


class DummySSEHandler:
    interceptor_callback = None

    def set_module(self, module_name):
        self.module_name = module_name

    def send_module_completed(self):
        return None

    def send_resolving_dependency(self, dependency_name):
        return None

    def set_current_model(self, model_name):
        self.model_name = model_name


class FakeProcessor:
    output_format = "flac"

    def execute_module(self, module_name, input_path, output_dir, interceptor_callback=None):
        from modules import get_module

        outputs = {}
        config = get_module(module_name)
        for stem_key, output_name in config["custom_output_names"].items():
            output_path = Path(output_dir) / f"{output_name}.flac"
            output_path.write_text(f"generated by {module_name}", encoding="utf-8")
            outputs[stem_key] = str(output_path)
        return outputs


def _build_services(library_root, tmp_path):
    repository = ProjectRepository(Database(str(library_root)))
    project_service = ProjectService(str(library_root), project_repository=repository)
    file_service = FileService(project_service, str(tmp_path / "uploads"))
    audio_service = AudioService(project_service, file_service)
    audio_service.processor = FakeProcessor()
    return repository, project_service, audio_service


def test_process_separation_persists_sqlite_snapshot_without_metadata_json(library_root, tmp_path, monkeypatch):
    monkeypatch.setattr("services.AudioService.precompute_waveforms_for_outputs", lambda outputs, output_dir: {})

    _, project_service, audio_service = _build_services(library_root, tmp_path)
    project_id = "20260327010101_song-demo"
    project_dir = library_root / project_id
    project_dir.mkdir(parents=True, exist_ok=True)
    (project_dir / "song.wav").write_text("original", encoding="utf-8")

    result = audio_service.process_separation(
        project_id,
        "song.wav",
        ["vocal_instrumental"],
        DummySSEHandler(),
        thumbnail="thumbs/demo.png",
        display_name="Song Demo",
    )

    snapshot = project_service.get_sqlite_project_snapshot(project_id)
    history = project_service.get_sqlite_history()

    assert result["id"] == project_id
    assert result["stems"] == ["base_instrumental.instrumental.flac", "base_vocals.vocal.flac"]
    assert result["executed_modules"] == ["vocal_instrumental"]
    assert result["thumbnail"] == "thumbs/demo.png"
    assert snapshot["project"]["name"] == "Song Demo"
    assert snapshot["status"]["original_file"] == "song.wav"
    assert snapshot["status"]["executed_modules"] == ["vocal_instrumental"]
    assert history[0]["original"] == "song.wav"
    assert not (project_dir / "metadata.json").exists()


def test_process_separation_updates_existing_project_and_history(library_root, tmp_path, monkeypatch):
    monkeypatch.setattr("services.AudioService.precompute_waveforms_for_outputs", lambda outputs, output_dir: {})

    _, project_service, audio_service = _build_services(library_root, tmp_path)
    project_id = "20260327020202_song-demo"
    project_dir = library_root / project_id
    project_dir.mkdir(parents=True, exist_ok=True)
    (project_dir / "song.wav").write_text("original", encoding="utf-8")

    audio_service.process_separation(
        project_id,
        "song.wav",
        ["vocal_instrumental"],
        DummySSEHandler(),
        display_name="Song Demo",
    )
    result = audio_service.process_separation(
        project_id,
        "song.wav",
        ["lead_backing"],
        DummySSEHandler(),
    )

    status = project_service.get_sqlite_project_status(project_id)

    assert result["executed_modules"] == ["lead_backing", "vocal_instrumental"]
    assert "lead_vocals.vocal.flac" in result["stems"]
    assert status["executed_modules"] == ["lead_backing", "vocal_instrumental"]
    assert project_service.get_sqlite_history()[0]["stems"] == sorted(result["stems"])


def test_unify_tracks_refreshes_sqlite_snapshot(library_root, tmp_path, monkeypatch):
    monkeypatch.setattr("services.AudioService.precompute_waveforms_for_outputs", lambda outputs, output_dir: {})
    monkeypatch.setattr("services.AudioService.precompute_waveform", lambda audio_path, output_path: Path(output_path).write_text("{}", encoding="utf-8"))
    monkeypatch.setattr("services.AudioService.sf.read", lambda path: (np.array([[0.1, 0.1], [0.2, 0.2]], dtype=np.float32), 44100))
    monkeypatch.setattr("services.AudioService.sf.write", lambda output_path, mixed, sr: Path(output_path).write_text("mixed", encoding="utf-8"))

    _, project_service, audio_service = _build_services(library_root, tmp_path)
    project_id = "20260327030303_song-demo"
    project_dir = library_root / project_id
    project_dir.mkdir(parents=True, exist_ok=True)
    (project_dir / "song.wav").write_text("original", encoding="utf-8")

    audio_service.process_separation(
        project_id,
        "song.wav",
        ["vocal_instrumental"],
        DummySSEHandler(),
        display_name="Song Demo",
    )

    new_track = audio_service.unify_tracks(project_id, ["base_vocals.vocal.flac"])
    snapshot = project_service.get_sqlite_project_snapshot(project_id)

    assert new_track == "base_vocals.vocal.unified.wav"
    assert new_track in snapshot["history"]["stems"]
    assert snapshot["status"]["executed_modules"] == ["vocal_instrumental"]
